// <auto-generated />
using System;
using ApiUsers.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiUsers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250624205112_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiUsers.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 6, 24, 14, 51, 11, 825, DateTimeKind.Local).AddTicks(6823),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Code = "GUEST",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 6, 24, 14, 51, 11, 825, DateTimeKind.Local).AddTicks(6835),
                            Name = "Guest"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SYS_ADMIN",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 6, 24, 14, 51, 11, 825, DateTimeKind.Local).AddTicks(6837),
                            Name = "System Administrator"
                        },
                        new
                        {
                            Id = 4,
                            Code = "INTERNAL",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 6, 24, 14, 51, 11, 825, DateTimeKind.Local).AddTicks(6838),
                            Name = "Internal"
                        });
                });

            modelBuilder.Entity("ApiUsers.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 6, 24, 14, 51, 11, 828, DateTimeKind.Local).AddTicks(8797),
                            Email = "default@default.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "RElBE0N/lV1NmUJNVbun3ZoQDtDHVIDIF5zsF32sjbykvHXS",
                            RolId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
